name: probe4physics
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch>=2.2
  - torchvision>=0.17
  - pip
  - datasets>=2.20
  - pyyaml>=6.0
  - hydra-core>=1.3
  - pandas>=2.0
  - scikit-learn>=1.4
  - pyarrow>=14
  - ffmpeg
  - av
  - datasets
  - huggingface_hub>=0.23
  - transformers>=4.41
  - diffusers>=0.37
  - accelerate>=0.30
  - safetensors>=0.4
